name: Build and Publish to GitHub Packages

on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: statens-pensjonskasse/public-actions-library/.github/workflows/build-library-node.yaml@dfdf5f4b576bc1a035b9e6471cd467e3ce876ff3 # v0.3.5
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      node-version: '21'
