name: Build and Publish to GitHub Packages

on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: statens-pensjonskasse/public-actions-library/.github/workflows/build-library-node.yaml@16c46c45d9a043d60b04f54e62d5bba197c0b94f # v0.2.14
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      node-version: '21'
